services:
  
  auth-application:
    image: farmacio-auth:0.1
    env_file:
      - app.env
    ports:
      - "5001:5001"
    depends_on:
      - users-database
    networks:
      - auth
  
  users-database:
    image: sha256:2b41d0be82839692f678a709e8b7dd6106ee4776b0e70759c59b067730058b04
    env_file:
      - app.env
    volumes:
      - userDB-volume:/var/opt/mssql
    ports:
      - "1433:1433"
    networks:
      - auth

volumes:
  userDB-volume:

networks:
  auth:
    driver: bridge