services:
  core-app:
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    environment:
      "ASPNETCORE_ENVIRONMENT": "Development"
      "CONNECTION_STRING": "host=farmacio-core-database;port=5432;database=farmacio;username=aleks;password=1234"
      "SECRET_KEY": "fb735a9fb746af971ce8410cc9af311209a842d936dde33cadb90acaa247d64a"
      "ACCESS_TOKEN_LIFETIME": "15"
      "REFRESH_TOKEN_LIFETIME": "30"
    depends_on:
      farmacio-core-database:
        condition: service_healthy
    ports:
      - '8080:8080'
      - '443:443'
  farmacio-core-database:
    image: postgres:16
    volumes:
      - core_db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "aleks"
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: "farmacio"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U aleks -d farmacio" ]
      interval: 2s
      timeout: 2s
      retries: 20
    ports:
      - '5433:5432'

volumes:
  core_db_volume: