services:
  core-app:
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    environment:
      "ASPNETCORE_ENVIRONMENT": "Development"
      "CONNECTION_STRING": "host=farmacio-core-database;port=5432;database=farmacio;username=aleks;password=1234"
      "SECRET_KEY": "fb735a9fb746af971ce8410cc9af311209a842d936dde33cadb90acaa247d64a"
      "ACCESS_TOKEN_LIFETIME": "15"
      "REFRESH_TOKEN_LIFETIME": "30"
    depends_on:
      farmacio-core-database:
        condition: service_healthy
    ports:
      - '8080:8080'
      - '443:443'
  
  farmacio-core-database:
    image: postgres:16
    volumes:
      - core_db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "aleks"
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: "farmacio"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U aleks -d farmacio" ]
      interval: 2s
      timeout: 2s
      retries: 20
    ports:
      - '5434:5432'
  
  statistic-broker:
    image: confluentinc/cp-kafka:7.2.15
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://statistic-broker:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
    
    volumes:
      - statistic-message-volume:/bitnami/kafka
    ports:
      - '29092:29092'
  
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.15
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - '22181:2181'
  
  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: kafka-ui
    ports:
      - 8090:8080
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=statistic-broker:29092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    links:
      - statistic-broker
      - zookeeper

volumes:
  core_db_volume:
  statistic-message-volume: