services:
  core-app:
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    environment:
      "ASPNETCORE_ENVIRONMENT": "Development"
      "CONNECTION_STRING": "host=farmacio-core-database;port=5432;database=farmacio;username=aleks;password=1234"
      "SECRET_KEY": "fb735a9fb746af971ce8410cc9af311209a842d936dde33cadb90acaa247d64a"
      "ACCESS_TOKEN_LIFETIME": "15"
      "REFRESH_TOKEN_LIFETIME": "30"
    depends_on:
      farmacio-core-database:
        condition: service_healthy
    ports:
      - '8080:8080'
      - '443:443'
  
  farmacio-core-database:
    image: postgres:16
    volumes:
      - core_db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "aleks"
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: "farmacio"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U aleks -d farmacio" ]
      interval: 2s
      timeout: 2s
      retries: 20
    ports:
      - '5434:5432'
  
  statistic-broker1:
    image: confluentinc/cp-kafka:8.0.0
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_BROKER_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@statistic-broker1:29093,2@statistic-broker2:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://statistic-broker1:29092,CONTROLLER://statistic-broker1:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://statistic-broker1:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      CLUSTER_ID: EmptNWtoR4GGWx-BH6nGLQ
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_DEFAULT_REPLICATION_FACTOR: 2
    ports:
      - "29092:29092"
      - "29093:29093"
      - "9092:9092"
    volumes:
      - statistic-message-volume1:/var/lib/kafka/data
    networks:
      - statistic-net
  
  statistic-broker2:
    image: confluentinc/cp-kafka:8.0.0
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_BROKER_ID: 2
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@statistic-broker1:29093,2@statistic-broker2:29093
      KAFKA_LISTENERS: PLAINTEXT://statistic-broker2:29092,CONTROLLER://statistic-broker2:29093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://statistic-broker2:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      CLUSTER_ID: EmptNWtoR4GGWx-BH6nGLQ
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_DEFAULT_REPLICATION_FACTOR: 2
    ports:
      - "29094:29092"
      - "29095:29093"
    volumes:
      - statistic-message-volume2:/var/lib/kafka/data
    networks:
      - statistic-net
  
  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: kafka-ui
    ports:
      - 8080:8080
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=statistic-broker1:29092,statistic-broker2:29092
    depends_on:
      - statistic-broker1
      - statistic-broker2
    networks:
      - statistic-net


networks:
  statistic-net:
    driver: bridge

volumes:
  core_db_volume:
  statistic-message-volume1:
  statistic-message-volume2: